### ISSUE TITLE
Malformed LIDAR data on outdoor FOREST dataset for Wilbur Robot

### ISSUE THREAD

**Issue by DanielChaseButterfield** [arplaboratory/CoPeD#4]
Hi, I've been employing this dataset for multi-robot SLAM, and found out that the messages on /wilbur/lidar_points are sometimes malformed (if not always) for the Outdoor FOREST sequence. For example, see the following message on that topic:

```
header: 
  seq: 43398
  stamp: 
    secs: 1684528268
    nsecs: 388045312
  frame_id: "wilbur/ouster_center_link"
height: 1
width: 79962
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "intensity"
    offset: 16
    datatype: 7
    count: 1
  - 
    name: "t"
    offset: 20
    datatype: 6
    count: 1
  - 
    name: "reflectivity"
    offset: 24
    datatype: 4
    count: 1
  - 
    name: "ring"
    offset: 26
    datatype: 2
    count: 1
  - 
    name: "ambient"
    offset: 28
    datatype: 4
    count: 1
  - 
    name: "range"
    offset: 32
    datatype: 6
    count: 1
is_bigendian: False
point_step: 48
row_step: 2905344
data: OMITTED BECAUSE OF SIZE
is_dense: True
```

Clearly, row_step / point_step should = width. However, 2905344/48 != 79962, but instead 2905344/48 = 60528. 

Is there any way that this could be corrected. For example, can the remaining entries in the buffer be safely ignored?

As far as I'm aware, /wilbur/lidar_points_center and /wilbur/lidar_points_front don't seem to suffer from the same issue.
